
# NOTE(flaper87): If any extra config files are required, it's possibled to
# "upload" them at this point. These files will be copied in the `/tmp` of the
# server (or container) where this role is running.
#- name: Upload config files
#  template:
#    src: "{{item}}"
#    dest: /tmp/{{item}}
#    backup: yes
#    mode: 0644
#  with_items:
#    - httpd.conf
#    - httpd-glance-main.conf

- include: hiera.yml

- name: Generate config files
  config_template:
    src: base.conf.j2
    dest: /tmp/neutron.conf
    config_overrides: '{{neutron_config}}'
    config_type: ini

# NOTE(flaper87): If external config fines were generated, copy them into memory
# following the example below. The registered variable will be used to create
# the config map.
- name: Read configs into memory
  slurp:
    src: "/tmp/neutron.conf"
  register: "neutron_conf"

- include: neutron-api.yml
- include: neutron-dhcp-agent.yml
- include: neutron-metadata-agent.yml
# NOTE(flaper87): we should do this iff the keystone-secret exists and keystone
# is enabled. Add checks for each.
- include: keystone.yml
